[package]
name = "self_update"
version = "0.4.3"
description = "Self updates for standalone executables"
repository = "https://github.com/jaemk/self_update"
keywords = ["update", "upgrade", "download", "release"]
categories = ["command-line-utilities"]
license = "MIT"
readme = "README.md"
authors = ["James Kominick <james.kominick@gmail.com>"]
exclude = ["/ci/*", ".travis.yml", "appveyor.yml"]

[dependencies]
serde_json = "1"
reqwest = "0.9"
tempdir = "0.3"
flate2 = "1"
tar = "0.4"
semver = "0.9"
pbr = "1"
hyper-old-types = "0.11.0"

